In [5]:
import sqlite3
import pandas as pd

### Load the tuning records from sqlite3 file

In [6]:
conn = sqlite3.connect("/var/tmp/pidtune.db")
df1 = pd.read_sql_query("SELECT * FROM Pose", conn)
df2 = pd.read_sql_query("SELECT * FROM PIDParam", conn)
df3 = df1.merge(df2, on='timestamp',how='inner')

### Check for $K_p$, $K_i$ and $K_d$ that yields the lowest `posx` error

In [11]:
df3.sort_values('posx', ascending=True)

,orientx,orienty,orientz,posx,posy,posz,timestamp,Kp,Ki,Kd
980,0,-0.000214,0,0.627255,0,0.000000,1675742022063409602,100,0.981,10
979,0,-0.000216,0,0.629519,0,0.000000,1675742016971186659,100,0.980,10
978,0,-0.000237,0,0.634984,0,0.000000,1675742011870841353,100,0.979,10
997,0,-0.000234,0,0.642672,0,0.000000,1675742108652439114,100,0.998,10
996,0,-0.000234,0,0.643899,0,0.000000,1675742103559281393,100,0.997,10
...,...,...,...,...,...,...,...,...,...,...
4,0,0.003578,0,1.901325,0,0.000001,1675737055931866497,100,0.005,10
14,0,0.003073,0,1.902364,0,0.000001,1675737106742790542,100,0.015,10
2,0,0.003698,0,1.907706,0,0.000001,1675737045763003094,100,0.003,10
1,0,0.003761,0,1.911341,0,0.000001,1675737040684023025,100,0.002,10
0,0,0.003824,0,1.915069,0,0.000001,1675737035607019046,100,0.001,10